apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashuwebapp1
  name: ashuwebapp1
  namespace: ashu-jci
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ashuwebapp1
  type: NodePort
status:
  loadBalancer: {}
